apiVersion: v1
kind: Service
metadata:
  name: service-provider-place-registration-service
spec:
  type: LoadBalancer
  selector:
    app: sp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070